################### RULES https://realm.github.io/SwiftLint/

disabled_rules:
    - todo
    - identifier_name
    - nesting
    - type_name
    - cyclomatic_complexity
#   - legacy_hashing
#   - line_length
#   - identifier_name 
#   - force_cast
#   - weak_delegate
#   - force_try
#   - function_parameter_count
#   - file_length
#   - function_body_length
#   - class_delegate_protocol #disabled this rule since it cannot track inheritance of protocol if protocols declared in different files
#   - operator_whitespace 

analyzer_rules:
  - unused_declaration
  - unused_import
opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  # - discouraged_none_name
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  # - file_header
  # - file_name
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  # - nslocalizedstring_key
  - number_separator
  # - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - return_value_from_void_function
  - single_test_class
  - sorted_first_last
  # - sorted_imports
  - static_operator
  - strong_iboutlet
  - test_case_accessibility
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  # - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

included:
  - FlowCrypt
  - FlowCryptUI
  - FlowCryptCommon
excluded: 
  - FlowCrypt/Core
  - FlowCrypt/Functionality/Imap


attributes:
  always_on_same_line:
    ["@objc"]
line_length: 140
function_body_length: 50

type_body_length:
  - 500 # Warning
  - 600 # Error

number_separator:
  minimum_length: 5
  minimum_fraction_length: 7

# warning_threshold: 1

reporter: "xcode"

### to disable rule
### // swiftlint:disable <rule>
