# fastlane/Fastfile
ENV["FASTLANE_EXPLICIT_OPEN_SIMULATOR"] = "1"

default_platform(:ios)

platform :ios do

  before_all do
    # installed via the semaphore plugin with `fastlane add_plugin semaphore`
    # setup_semaphore
    cocoapods(
      try_repo_update_on_error: true
    )
  end

  desc "Build for UI tests"
  lane :build do
    xcbuild(
       workspace: "FlowCrypt.xcworkspace",
       scheme: "Debug FlowCrypt",
       configuration: "Debug",
       xcargs: "-sdk iphonesimulator SYMROOT='/var/tmp/'"
    )
    sh("rm -rf ~/git/flowcrypt-ios/appium/FlowCrypt.app")
    sh("mv /var/tmp/Debug-iphonesimulator/FlowCrypt.app ~/git/flowcrypt-ios/appium/")
  end

  desc "Run Swift tests"
  lane :test do
    scan(
      scheme: "FlowCryptAppTests"
    )
  end

  desc "Distribute app"
    lane :distribute do
        build_app(
          workspace: "FlowCrypt.xcworkspace",
          configuration: "Debug",
          scheme: "Debug FlowCrypt",
          output_name: "app.ipa"
          # output_directory: "path/to/dir", # Destination directory. Defaults to current directory.
          # output_name: "my-app.ipa",       # specify the name of the .ipa file to generate (including file extension)
        )

        firebase_app_distribution(
            app: ENV['FIREBASE_APP_ID'],
            service_credentials_file: "firebase_credentials.json"
        )

    end

end

