# fastlane/Fastfile
default_platform(:ios)

platform :ios do

  before_all do
    # installed via the semaphore plugin with `fastlane add_plugin semaphore`
    setup_semaphore
  end

  desc "Cocoapod update"
  lane :cocoapod_update do 
    cocoapods(
      try_repo_update_on_error: true
    )

  end

  desc "Run UI Tests"
  lane :test_ui do
    reset_simulator_contents()
    scan(
      scheme: "FlowCryptUITests",
      clean: false,
      reset_simulator: true,
      reinstall_app: true,
      skip_build: true,    
      disable_slide_to_type: true  
      devices: ["iPhone 11 Pro Max"]
)

  end

  desc "Run Tests"
  lane :test do 
    scan(
      scheme: "FlowCryptTests",
      skip_build: true    
  )

  end

  desc "Build"
  desc "Build without code sign. Just to see if the build is working"
  lane :build do |options|
    gym(
      scheme: "FlowCrypt",
      skip_package_ipa: true,
      skip_archive: true,
      silent: true,
      clean: true,
      skip_codesigning: true
  )

  end

  desc "Record ui tests"
  lane :record_tests do
	reset_simulator        
	sh("./record.sh")
  end

  desc "Build app, run tests, run UI test"
  lane :do_everything do 
    cocoapod_update
#   build
#   test
    test_ui
    # record_tests
  end

  desc "Reset simulator content"
  lane :reset_simulator do
	reset_simulator_contents()
  end

end

