# fastlane/Fastfile
ENV["FASTLANE_EXPLICIT_OPEN_SIMULATOR"] = "1"

default_platform(:ios)

platform :ios do

  before_all do
    # installed via the semaphore plugin with `fastlane add_plugin semaphore`
    # setup_semaphore
    cocoapods(
      try_repo_update_on_error: true
    )
  end

  desc "Build for CI testing"
  lane :build do |options|
    gym(
      scheme: "Debug FlowCrypt",
      skip_package_ipa: true,
      skip_archive: true,
      silent: true,
      clean: false,
      skip_codesigning: true,
      configuration: "Debug"
    )
  end

  desc "Build for UI testing"
  lane :build_e2e do
    xcbuild(
       workspace: "FlowCrypt.xcworkspace",
       scheme: "Debug FlowCrypt",
       configuration: "Debug",
       xcargs: "-sdk iphonesimulator SYMROOT='/var/tmp/'"
    )
    # sh("mv /var/tmp/Debug-iphonesimulator/FlowCrypt.app ./appium/FlowCrypt.app")
  end

  desc "Build for UI testing"
  lane :move_e2e do
    sh("mv /var/tmp/Debug-iphonesimulator/FlowCrypt.app appium/")
  end

  desc "Build app and run Swift tests"
  lane :swift_tests do
    build
    scan(
      scheme: "FlowCryptAppTests",
      skip_build: true
    )
  end

end

