# Uncomment the lines below you want to change by removing the # in the beginning

devices([
  # "iPhone 8",
  "iPhone 11",
])

# languages([
#   "en-US",
#   "de-DE",
#   "it-IT",
#   ["pt", "pt_BR"] # Portuguese with Brazilian locale
# ])


# Where should the resulting screenshots be stored?
# output_directory("./screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
erase_simulator(true)
reinstall_app(true)
stop_after_first_error(true)
disable_slide_to_type(true)

